# Generated by Django 5.1.5 on 2025-01-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='Edu_Service',
        ),
    ]
