# Generated by Django 5.1.5 on 2025-01-24 13:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_service_edu_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu_service',
            name='color',
            field=colorfield.fields.ColorField(default='#fff', image_field=None, max_length=25, samples=None),
        ),
    ]
