# Generated by Django 5.1.5 on 2025-01-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
