# Generated by Django 5.1.5 on 2025-01-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_team_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
